const demoProducts = [
  {
    name: "Everyday Cotton Crewneck Tee",
    slug: "everyday-cotton-crewneck-tee",
    category: "Clothing",
    brand: "Northline",
    description: "A soft cotton crewneck tee made for comfortable everyday wear.",
    stock: 32,
    price: 18.99,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p1-1.jpg"],
  },
  {
    name: "Relaxed Fit Oxford Shirt",
    slug: "relaxed-fit-oxford-shirt",
    category: "Clothing",
    brand: "Harbor & Field",
    description: "A relaxed button-down shirt in breathable woven cotton.",
    stock: 18,
    price: 46.5,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p1-2.jpg"],
  },
  {
    name: "Soft Knit Pullover",
    slug: "soft-knit-pullover",
    category: "Clothing",
    brand: "Northline",
    description: "A lightweight knit pullover with a classic, easy-to-layer fit.",
    stock: 14,
    price: 54,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p2-1.jpg"],
  },
  {
    name: "Weekend Zip Hoodie",
    slug: "weekend-zip-hoodie",
    category: "Clothing",
    brand: "Daymark",
    description: "A brushed-fleece zip hoodie with a roomy hood and front pockets.",
    stock: 21,
    price: 42.99,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p3-1.jpg"],
  },
  {
    name: "Straight Cut Chino Pants",
    slug: "straight-cut-chino-pants",
    category: "Clothing",
    brand: "Harbor & Field",
    description: "Versatile straight-leg chinos with a touch of stretch.",
    stock: 16,
    price: 58,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p4-1.jpg"],
  },
  {
    name: "Lightweight Quilted Jacket",
    slug: "lightweight-quilted-jacket",
    category: "Clothing",
    brand: "Daymark",
    description: "A packable quilted jacket for cool mornings and changing weather.",
    stock: 9,
    price: 89.95,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p5-1.jpg"],
  },
  {
    name: "Canvas City Backpack",
    slug: "canvas-city-backpack",
    category: "Bags",
    brand: "Fieldwork",
    description: "A durable canvas backpack with a padded laptop sleeve.",
    stock: 13,
    price: 64,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p6-1.jpg"],
  },
  {
    name: "Compact Everyday Crossbody",
    slug: "compact-everyday-crossbody",
    category: "Bags",
    brand: "Fieldwork",
    description: "A compact crossbody bag with an adjustable strap and zip pockets.",
    stock: 17,
    price: 38.5,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p1-1.jpg"],
  },
  {
    name: "Classic Low-Top Sneakers",
    slug: "classic-low-top-sneakers",
    category: "Footwear",
    brand: "Stridewell",
    description: "Clean low-top sneakers with a cushioned footbed for daily use.",
    stock: 24,
    price: 72,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p2-1.jpg"],
  },
  {
    name: "Trail Ready Walking Shoes",
    slug: "trail-ready-walking-shoes",
    category: "Footwear",
    brand: "Stridewell",
    description: "Supportive walking shoes with grippy soles for light trails.",
    stock: 11,
    price: 94.99,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p3-1.jpg"],
  },
  {
    name: "Minimal Leather Card Holder",
    slug: "minimal-leather-card-holder",
    category: "Accessories",
    brand: "Common Goods",
    description: "A slim card holder with four card slots and a center pocket.",
    stock: 27,
    price: 24,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p4-1.jpg"],
  },
  {
    name: "Everyday Web Belt",
    slug: "everyday-web-belt",
    category: "Accessories",
    brand: "Common Goods",
    description: "A sturdy woven belt with an adjustable metal buckle.",
    stock: 30,
    price: 19.5,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p5-1.jpg"],
  },
  {
    name: "Insulated Travel Tumbler",
    slug: "insulated-travel-tumbler",
    category: "Home & Kitchen",
    brand: "Brightpath",
    description: "A double-wall stainless steel tumbler that keeps drinks at temperature.",
    stock: 35,
    price: 27.99,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p6-1.jpg"],
  },
  {
    name: "Stoneware Breakfast Mug Set",
    slug: "stoneware-breakfast-mug-set",
    category: "Home & Kitchen",
    brand: "Brightpath",
    description: "A pair of sturdy stoneware mugs with a matte glazed finish.",
    stock: 19,
    price: 31,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p1-2.jpg"],
  },
  {
    name: "Soft Woven Throw Blanket",
    slug: "soft-woven-throw-blanket",
    category: "Home & Kitchen",
    brand: "Hearthside",
    description: "A cozy woven throw blanket sized for a sofa or favorite chair.",
    stock: 12,
    price: 49.99,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p2-1.jpg"],
  },
  {
    name: "Acacia Serving Board",
    slug: "acacia-serving-board",
    category: "Home & Kitchen",
    brand: "Hearthside",
    description: "A smooth acacia wood serving board for snacks and small bites.",
    stock: 15,
    price: 36,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p3-1.jpg"],
  },
  {
    name: "Adjustable Desk Lamp",
    slug: "adjustable-desk-lamp",
    category: "Home & Office",
    brand: "Brightpath",
    description: "A compact desk lamp with an adjustable neck and warm LED light.",
    stock: 10,
    price: 44.95,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p4-1.jpg"],
  },
  {
    name: "Recycled Paper Notebook Trio",
    slug: "recycled-paper-notebook-trio",
    category: "Home & Office",
    brand: "Papertrail",
    description: "Three lay-flat notebooks made with recycled paper for notes and lists.",
    stock: 40,
    price: 16,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p5-1.jpg"],
  },
  {
    name: "Wireless Compact Keyboard",
    slug: "wireless-compact-keyboard",
    category: "Electronics",
    brand: "Keyhaven",
    description: "A quiet wireless keyboard with a compact layout for home or travel.",
    stock: 8,
    price: 69.99,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p6-1.jpg"],
  },
  {
    name: "Foldable Laptop Stand",
    slug: "foldable-laptop-stand",
    category: "Electronics",
    brand: "Keyhaven",
    description: "A lightweight foldable stand that raises a laptop to a comfortable height.",
    stock: 22,
    price: 32.5,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p1-1.jpg"],
  },
  {
    name: "Insulated Stainless Water Bottle",
    slug: "insulated-stainless-water-bottle",
    category: "Accessories",
    brand: "Brightpath",
    description: "A leak-resistant stainless steel bottle for commutes and day trips.",
    stock: 25,
    price: 29,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p2-1.jpg"],
  },
  {
    name: "Polarized Everyday Sunglasses",
    slug: "polarized-everyday-sunglasses",
    category: "Accessories",
    brand: "Daymark",
    description: "Lightweight polarized sunglasses with a versatile everyday shape.",
    stock: 14,
    price: 52,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    banner: null,
    images: ["/images/sample-products/p3-1.jpg"],
  },
  {
    name: "Soft Cotton Bath Towel Set",
    slug: "soft-cotton-bath-towel-set",
    category: "Home & Kitchen",
    brand: "Hearthside",
    description: "A two-piece cotton towel set with a soft feel and quick-drying weave.",
    stock: 20,
    price: 39,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p4-1.jpg"],
  },
  {
    name: "Insulated Lunch Tote",
    slug: "insulated-lunch-tote",
    category: "Bags",
    brand: "Fieldwork",
    description: "A reusable insulated lunch tote with a wipe-clean lining.",
    stock: 16,
    price: 28.5,
    rating: 0,
    numReviews: 0,
    isFeatured: false,
    banner: null,
    images: ["/images/sample-products/p5-1.jpg"],
  },
];

export default demoProducts;
