const sampleData = {
  users: [
    // Add admin user here like this
    // {
    //   name: "",
    //   email: "",
    //   password: "",
    //   role: "admin",
    // },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
    },
  ],
  products: [
    {
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Classic Polo style with modern comfort",
      images: [
        "https://utfs.io/f/y8H5xxEpLidgLIEhmyKjYr2TBlKW8NZHAQqV4Lk6vumpD1yE",
        "https://utfs.io/f/y8H5xxEpLidg0yDVBJQSYXyoV2v5Bct1umr8eAjJs30nKgZN",
      ],
      price: 59.99,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Men's Dress Shirts",
      description: "Timeless style and premium comfort",
      images: [
        "https://utfs.io/f/y8H5xxEpLidg6yO63vfL2UEsBaAhg9vwMCVrH0dScb1XQGx5",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "https://utfs.io/f/y8H5xxEpLidgitf276s81EXxSp7VCvfDLubrsjRWic5GaIMB",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "https://utfs.io/f/y8H5xxEpLidgql3oURit7hbnuamkwUcj1ZWRHdvDFGOo8XgQ",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "https://utfs.io/f/y8H5xxEpLidgql3oURit7hbnuamkwUcj1ZWRHdvDFGOo8XgQ",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "https://utfs.io/f/y8H5xxEpLidgql3oURit7hbnuamkwUcj1ZWRHdvDFGOo8XgQ",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
}

export default sampleData
